baseURL = "http://ricardogalvez.design/"
languageCode = "en-us"
title = "ricardogalvez.design"
theme = "blank"
relativeURLs = "true"
enableRobotsTXT = "true"

[params]
    author="Ricardo Eric Gálvez"
    subtitle="Ricardo E. Gálvez"
    # javascript vendor path
    vendorPath = "js/vendor/"
    customJsPath = "js/experiments/"
    # Image params:
    postImageSqip = ""
    postImage1x = ""
    postImage2x = ""
    postImage3x = ""
    postImageAlt = ""
    # the figure catption param:
    figcaption = ""
    # svg source and clip path classes (for declaring the path and setting a color):
    svgSource = ""
    svgClipObjectClass = ""
    svgColorClass = ""
    # portfolio landing page image param:
    portfolioHeroSqip = ""
    portfolioHero1x = ""
    portfolioHero2x = ""
    portfolioHero3x = ""
    portfolioHeroAlt = ""
    placeHolderSVG = "/images/placeHolding.svg"
    [params.cloudinary]    
        class = "cld-responsive"
    [params.twitter]
        name = "twitter"
        site = "@rixblargh"
        title = "Ricardo E. Galvez"
        description = "Designer / Developer"
        card = "summary_large_image"
        url = "https://twitter.com/rixblargh"
        iconClass = "twitter"
    [params.github]
        name = "github"
        userName = "@ricardoom"
        url = "https://github.com/ricardoom"
    [params.linkedin]
        name = "linkedin"
        url = "https://www.linkedin.com/in/ricardogalvez/"
        iconClass = "linkedin"
    # [params.instagram]
    #     name = "instagram"
    #     userName = "@rixblargh"
    #     url = "https://www.instagram.com/ricardogalvez.design/"
    #     iconClass = "instagram"
    # [params.dribbble]
    #     name = "dribbble"
    #     userName = "@rixblargh"
    #     url = "https://dribbble.com/ricardoom"
    #     iconClass = "instagram"
    [params.openGraph]
        image = "images/twitterCard@2x.jpg"
    [params.portfolio]
        projectRoles = []
        projectClients = []
        projectDate = ""
        projectCredits = []
    # some classes we want to expose to hugo:
    [params.classes]
        homePage = "home-page"
        innerPage = "inner-page"
        portfolioPage = "portfolio-page"
        aboutPage = "about-page"
        blogPage = "blog-page"
        experimentsPage = "experiments-page"
    [params.vendors]
        matterJS = "matter/matter.min.js"
        paperJS = "paper/paper-full.js"
        p5JS = "p5/p5.js"
        svgJS = "svg/svg.min.js"
        threeJS = "three/three.min.js"
        gsapJS = "gsap/3.6.0/gsap.min.js"
        animeJS = "anime/anime.min.js"
[permalinks]
    post = "/:year/:month/:title/"

[menus]
    # [[menu.main]]
    #     identifier = "blog"
    #     name = "blog"
    #     title = "the blog section"
    #     url = "/posts/"
    #     weight = 3
    # [[menu.main]]
    #     identifier = "experiments"
    #     name = "experiments"
    #     title = "experiments"
    #     url = "/experiments/"
    #     weight = 2
    [[menu.main]]
        identifier = "portfolio"
        name = "portfolio"
        title = "portfolio"
        url = "/portfolio/"
        weight = -10

[resources]